# Generated by Django 5.1.4 on 2024-12-18 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academyYear', models.IntegerField()),
                ('academyMonth', models.IntegerField()),
                ('startDate', models.DateField()),
                ('classroom_name', models.CharField(max_length=100)),
                ('isPrimary', models.BooleanField(default=False)),
                ('Branches', models.CharField(choices=[('KL', 'Kuala Lumpur'), ('SGR', 'Selangor')], max_length=100)),
                ('IsFranchiseStaff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('dob', models.DateField()),
                ('profileImage', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('birthCountry', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('role', models.CharField(choices=[('Management', 'Management'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Account', 'Account'), ('Teacher', 'Teacher')], max_length=100)),
                ('isWebAccess', models.BooleanField(default=False)),
                ('isMobileAccess', models.BooleanField(default=False)),
                ('doj', models.DateField()),
                ('isExternal', models.BooleanField(default=False)),
                ('staffNRIC', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_nric_format', message='Please use XXXXXX-XX-XXXX format.', regex='^\\d{6}-\\d{2}-\\d{4}$')])),
            ],
        ),
    ]
