# Generated by Django 5.1.4 on 2024-12-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
