# Generated by Django 5.1.4 on 2024-12-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_app', '0003_children_childrenschool_finance_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenschool',
            name='academyMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='childrenschool',
            name='academyYear',
            field=models.IntegerField(),
        ),
    ]
