# Generated by Django 5.1.4 on 2024-12-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_app', '0004_alter_childrenschool_academymonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='parentPhone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='parents',
            name='parentPhone2',
            field=models.BigIntegerField(),
        ),
    ]
